// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SierpinskiTetrahedron")>]
[<assembly: AssemblyProductAttribute("AardvarkSandBox")>]
[<assembly: AssemblyDescriptionAttribute("Aardvark SandBox")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SierpinskiTetrahedron"
    let [<Literal>] AssemblyProduct = "AardvarkSandBox"
    let [<Literal>] AssemblyDescription = "Aardvark SandBox"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
